### PR TITLE
Added endpoint /fmeproxy as a new controller

### PR DESCRIPTION
**Pull request by maan002**
New endpoint for the FME Server-plugin

### CODE REVIEW

**Comment by Hallbergs** [comment]
LGTM. I merged develop and added the settings to web.config so it will be easier for others to set up.

**Review by Hallbergs — APPROVED** [review]

**Comment by Hallbergs** [comment]
@maan002 BTW, did you test if the Admin UI for the FME-plugin worked with .NET?

**Comment by maan002** [comment]
Yes, of course (this morning :)

**Comment by Hallbergs** [comment]
Wonderful!

**Pull request merged**
