### PR TITLE
Feature/655 plugin bookmarks

### PR DESCRIPTION
**Pull request by jesade-vbg**
#655 

First version of Bookmarks plugin.

### CODE REVIEW

**Review by jacobwod — CHANGES_REQUESTED** [review]
Have you really changed anything in README.md? If not, it looks like you might have an issue with line endings. Please ensure you use LF, which already should be enforced by GIT, as per `.gitattributes`:
Skärmavbild 2021-02-16 kl  13 35 41

**Comment by jesade-vbg** [comment]
I hope I resolved the CRLF error. It must have happend when merged.
Note that there is no .gitattributes file where this readme is located.

**Comment by jesade-vbg** [comment]
I think all .md-files in root has CRLF. :/

**Review by jacobwod — CHANGES_REQUESTED** [review]
Please just revert README.md (unless you've really made changes - in that case we'll have a look into how it can be fixed later), right now it's blocking your PR.

**Comment by jesade-vbg** [comment]
> Please just revert README.md (unless you've really made changes - in that case we'll have a look into how it can be fixed later), right now it's blocking your PR.

I thought I reverted. I'll look again.
https://github.com/hajkmap/Hajk/pull/672/commits/a1172abd233c6b5c9b80595af2ac3ef7137cc89d

**Comment by jacobwod** [comment]
In that case it looks like you haven't pushed it:
Skärmavbild 2021-02-17 kl  08 06 23

**Comment by jacobwod** [comment]
I've just pushed README with 'LF' endings to `develop`. Please do `git merge develop` in your branch, that should fix it.

**Review by jacobwod — APPROVED** [review]

**Comment by jacobwod** [comment]
It's merge. Just one more thing: how do you activate this plugin in admin? Perhaps you missed to commit the files from `new-admin`?

**Comment by jesade-vbg** [comment]
The feature branch has been removed so I created: [https://github.com/hajkmap/Hajk/tree/fix/missing-bookmarks-admin-655](url)
I hope this is ok.

**Comment by jacobwod** [comment]
Absolutely, they get deleted on successful merge just so we don't have a lot of merged branches on `origin`.

**Pull request merged**
