### PR TITLE
Added date prop to print

### LINKED ISSUE #1196: Print: Add current date to printout
A user has requested we add a date to Print. Preferably the date should be printed where the "disclaimer" and "copyright" is on the printed image (see red marking in image below).

Skärmbild 2022-09-29 135858

### PR DESCRIPTION
**Pull request by OlofSvahnVbg**
closes #1196

### CODE REVIEW

**Comment by OlofSvahnVbg** [comment]
Havent thought about adding to admin, but would probably be easy.

**Comment by OlofSvahnVbg** [comment]
I checked with colleagues regarding date in admin, but no one knew where to add this. Maybe we can check on that later on?

**Comment by Hallbergs** [comment]
> I checked with colleagues regarding date in admin, but no one knew where to add this. Maybe we can check on that later on?

Yes, sure. I would say we should add it to the print-tool-section in admin? Otherwise there will be no way to enable the date in print without messing with the config files manually?

**Comment by OlofSvahnVbg** [comment]
> 

Agreed.

**Comment by jesade-vbg** [comment]
I totally forgot to mention the needed Admin changes to Olof. We will create a new Issue with the needed changes and assign it to us.

**Pull request merged**
