### PR TITLE
Update configuration files in backend

### PR DESCRIPTION
**Pull request by victoraxbom**
New layer and map files with a basic configuration for the first startup.
You though need to set up the proxy to be able to search

Fixes issue #425

### CODE REVIEW

**Comment by jacobwod** [comment]
We'll look into this today. 👍

**Comment by jacobwod** [comment]
It looks fine here, good job @victoraxbom. I will merge it, but I don't know how we should solve the WFS problem. It'd be so nice to have a working search box, but that would require an open, meaningful WFS service in the same extent as our default map is.

**Comment by victoraxbom** [comment]
@jacobwod Yes, it would be perfect if the search would work right of the box. There is an open WFS included in the config files which works fine, the problem is CORS, which the proxy solves by adding the cors headers to the response from the wfs server. Don't know if anyone have another solution? 
Maybe the proxy could be pre-configured in the release

**Comment by jacobwod** [comment]
Ah I see. I don't understand why they provide an "open" WFS service but don't send the `Access-Control-Allow-Origin: *` header.

**Comment by jacobwod** [comment]
I would be cautions with adding the proxy component into the default configuration however (even if it'd solve this current problem). The reason is that adding proxy adds complexity to the system and introduces another point of possible failure. We've previously had problems with the included .NET proxy and have disabled it since, in favour of NGINX's proxy module which is more robust. 

**To sum up: it should be up to the admin to decide whether to use proxy or not, but by default we should keep it simple.**

**Pull request merged**
