### PR TITLE
Revert "Vt/core changes 4"

### PR DESCRIPTION
**Pull request by sweco-sesqqq**
Reverts hajkmap/Hajk#716

Seems like you've forgotten to include the package.json? 
image

### CODE REVIEW

**Comment by sweco-sesqqq** [comment]
@sweco-semtto I had to revert your PR. See image above. Probably some dependecies missing?

**Comment by sweco-semtto** [comment]
Reasonable, I'll look at it.

**Comment by sweco-semtto** [comment]
The missing dependencies have now been added.

**Comment by Hallbergs** [comment]
Could you please merge develop into your branch and then create a new pr? :)

**Comment by sweco-semtto** [comment]
No problems at all, already done, :)

**Pull request merged**
