### PR TITLE
Locking WFST edit layers with AD

### PR DESCRIPTION
**Pull request by persoderstrom**

### CODE REVIEW

**Comment by jacobwod** [comment]
I checked it out locally and ran into a couple of issues.

**Label says that all edit layers will be active if none is checked. **
That seems to be wrong: client shows no layers if none is checked.
Skärmavbild 2021-04-08 kl  10 58 00
Skärmavbild 2021-04-08 kl  10 57 42

**I can not save the Edit plugin in admin**
Also, please use only English in code.
Skärmavbild 2021-04-08 kl  10 56 24

**Please note**
Because of those issues, I was unfortunately unable to check if the intended functionality itself (i.e. filtering of activeServices) is working properly. 

**Backend**
It can be good to know that thoses tests were performed on the NodeJS backend.

**Review by jacobwod — CHANGES_REQUESTED** [review]
I checked it out locally and ran into a couple of issues.

### Label says that all edit layers will be active if none is checked.
That seems to be wrong: client shows no layers if none is checked.
Skärmavbild 2021-04-08 kl  10 58 00
Skärmavbild 2021-04-08 kl  10 57 42


### I can not save the Edit plugin in admin
As soon as I try to save (no matter if I actually select zero, one or many services in the list), I get the error below. (Also, please use only English in code.)
Skärmavbild 2021-04-08 kl  10 56 24


### Please note
Because of those issues, I was unfortunately unable to check if the intended functionality itself (i.e. filtering of activeServices) is working properly. 


### Backend
It can be good to know that thoses tests were performed on the NodeJS backend.

**Comment by persoderstrom** [comment]
1. I also noticed that if you use api/**v2**, client shows no layers if none is checked. The same goes for layers in **search tool**. api/**v1** works OK!
2. It seems that map config from Hajk2 does not work. Edit tool now use the same object structure {id:, visibleForGroups:} as the search tool. Will be fixed.

**Comment by jacobwod** [comment]
Hi @persoderstrom!

1. True, but I can only see it as the correct behaviour: if no service is selected, none should be visible. The way it was previously was kind of the other way around.
2. I doubt that I was using config from Hajk2, as you know we've been using v3 forever.

**Comment by persoderstrom** [comment]
I copied the behavior from search tool. But I agreee, only chosen layers should be shown,

**Comment by persoderstrom** [comment]
I pushed a new commit. It solves problems if visibleForGroups was undefined for services.

**Review by jacobwod — CHANGES_REQUESTED** [review]
@perosoderstrom , I'm not sure why but you're PR includes a lot of files that I'm sure you haven't changed (please see the "Files changed" tab). Please ensure that the PR only includes files you actually changed.

**Comment by jacobwod** [comment]
Somehow this PR still includes unwanted files. Please see mail @perosoderstrom .

**Comment by persoderstrom** [comment]
Closing this pull request. A new PR will be created from a new branch.

**Pull request closed without merging**
