### PR TITLE
Edit plugin: possibility of locking WFST edit layers with AD

### PR DESCRIPTION
**Pull request by persoderstrom**

### CODE REVIEW

**Comment by jacobwod** [comment]
Hi @perosoderstrom! This PR looks way better than before. But it's a big change that needs testing, so allow some time for us to test this from your feature branch (ad-for-edit-layers) _before_ we merge this into develop. OK?

**Comment by persoderstrom** [comment]
Good to hear! Take your time to test!

**Review by jacobwod — APPROVED** [review]
I've done the following tests:
- NodeJS backend
- Latest code from develop (merged in to this branch prior my checks)
- Tested with `AD_LOOKUP_ACTIVE` both `true` and `false`
- Tested with `"experimentalNewApi"` both `true` and `false`

Everything seems to work out fine and behave as expected:
- With AD lookup _inactive_ all WFST services that are active in map will be shown
- With AD lookup _active_ only those services that user has access to are shown
- With the new consolidated loading (v2 of API) the WFST layers that are not needed are _not_ visible in the layers repository.

I assume you've developed towards the .NET backend (I've seen changes in those files). 

**I've noticed that keeping old data can lead to unexpected behaviour. Deactivating and activating the Edit plugin solves this.**

Good job!

**Comment by persoderstrom** [comment]
Thanks @jacobwod and @Hallbergs for reviewing.
This PR should close #535.

**Pull request merged**
