### PR TITLE
Feature/1257 highlight active layers

### PR DESCRIPTION
**Pull request by LeeBadal**
# Feature/1257

Improve visibility between selected/not-selected in LayerSwitcher and active/non-active layers in bottom Snackbar.
## Screenshots
Adds a bold font style to the text of selected active layers in the layer switcher:
image

Adds a bold font to snackbar for selected layers, toggle is triggered by clicking the visibility icon.
image

## How:
**LayerGroup/LayerItem** Implements a function getCaption(caption,visible) that returns the appropriate styled component depending on visible argument.
**BreadCrumb.js** (bottom snackbar) uses the **hidden** variable which is related to the visibilityIcon toggle.

Would have preferred to use the same pattern/reuse function, however implemented in the logic similar to component-related code to preserve file-level consistency.

### CODE REVIEW

**Comment by Hallbergs** [comment]
@linusfj can you take a look at this? I saw that you opened the issue a while back. Could this be incorporated into the new layerSwitcher that your organization is working on?

**Comment by linusfj** [comment]
We've developed a similar solution on our branch for the new `LayerSwitcher` (#1380). In our implementation, we've emphasized layer and group names in the `LayerSwitcher` using bold text. Your suggestion to extend this bold styling to breadcrumbs as well is a good addition.

I suggest we approve this pull request and subsequently integrate these changes into the new `LayerSwitcher` branch.

**Review by linusfj — APPROVED** [review]

**Review by Hallbergs — CHANGES_REQUESTED** [review]
Wouldn't it be easier to put the visible check directly in the style-tag? That way we could avoid alot of code. Something like:
```js
<HeadingTypography sx={toggled ? { fontWeight: "bold" } : null}>
     {this.state.name}
</HeadingTypography>
```
Since you're using a component that already styled (`HeadingTypography`) another clean route could be to put the fontWeight-handling there and pass a prop to control it.

**Comment by jacobwod** [comment]
I agree with @Hallbergs. 

Additionally: can you consider making the bold styling "bubble" upwards in the tree, so that a group that has enabled layers also becomes bold? (In your screenshot @LeeBadal, it'd be bolding the _Länsstyrelsen_ group.) 

Thanks!

**Comment by LeeBadal** [comment]
@Hallbergs Agree, done.

@jacobwod 
Sure, 
image
image
image

**Review by Hallbergs — APPROVED** [review]

**Comment by Hallbergs** [comment]
Nice, gj!

**Comment by jacobwod** [comment]
Hi @LeeBadal! Does this really work for top-level groups? Cause I'm having with my top-level groups. 

One difference between my top-level groups and other groups further down is the check-all toggle.

Perhaps this requires the toggle to be work?

Skärmavbild 2023-10-30 kl  10 24 43

**Comment by jacobwod** [comment]
Update, I've fixed it - ensure to grab the latest develop where it's been cherry-picked as of 3e2f3391445711e229842b3e4c019b129dedd641.

**Pull request merged**
