### PR TITLE
Feature/orebro tsm 2

### PR DESCRIPTION
**Pull request by Sunix71**
A development of the tool document manager 2.0 in new-admin so that you can select multiple events in a story map. And in new-client so that you can click on a document link and get multiple events at the same time. You can now also choose to place an event on a headline menu.

### CODE REVIEW

**Review by Hallbergs — CHANGES_REQUESTED** [review]
It seems that the `MenuConnectionSelector` is duplicated? The code is basically the same between all three components. You should create one generic component and re-use that one.

I would suggest reading up on "Thinking in react" or the docs, see: https://beta.reactjs.org/.

**Comment by Sunix71** [comment]
Okay, now I have rewritten the code in one component, but I don't know if it's particularly generic because there are 3 different separate columns being displayed. But with this, I may be one step closer to the goal anyway. Thank you for input !

**Comment by Hallbergs** [comment]
Just added an example of how it can be made more generic. Test it out, and let me know if it works.

**Comment by Sunix71** [comment]
It works very well and is generic in its construction. Very good.

**Comment by Hallbergs** [comment]
Gonna let @jacobwod test with his config, then we can merge

**Comment by jacobwod** [comment]
Tested, seems to work as intended so it's good to go for me.

**Review by Hallbergs — APPROVED** [review]

**Pull request merged**
