### PR TITLE
1200 admin marginals and date

### LINKED ISSUE #1200: Add increased marginals and date printout to admin
We should add "larger marginals" ( #1174 ) and "date printout" ( #1196 ) to admin. I guess that's it. See example for "date" below:

image

And example for larger margins below: 

image

### LINKED ISSUE #1203: Shrink north arrow
The north arrow should be made smaller. When the user selects "Rubriktext m.m. i marginalerna" the map image is cropped to fit the height of the north arrow, and subsequently the map image gets a bit "thin". To avoid this the north arrow could be made smaller, allowing the map image to be taller.

image

image

### PR DESCRIPTION
**Pull request by OlofSvahnVbg**
Closes #1200
Closes #1203

### CODE REVIEW

**Review by Hallbergs — DISMISSED** [review]

**Comment by jacobwod** [comment]
I think this is great. The only problem I run into is with our logo (which seems bigger than the one you use?). Can we handle it somehow, but shrinking if some size is exceeded, similarly to how you've done it with the north arrow in #1203?

**Review by jacobwod — DISMISSED** [review]
Looks fine but please see separate comment considering the logo size.

**Comment by OlofSvahnVbg** [comment]
@jacobwod We decided on adding a northArrowMaxWidth for various reasons. Some users might be inclined to have different max values for logo and north arrow, depending on preference.

**Review by Hallbergs — APPROVED** [review]
lgtm. Merge when you feel ready!

**Pull request merged**
