### PR TITLE
Feature/855 fir plugin

### PR DESCRIPTION
**Pull request by jesade-vbg**
@maan002 will make a separate PR for backend related changes (later this day).

### CODE REVIEW

**Comment by Hallbergs** [comment]
Just out of curiosity, this plugin will only work if you use the .NET-backend?

**Comment by jesade-vbg** [comment]
I would probably work with nodejs backend, except for the exports, EDP etc, and the AD-filtering which has specific code in .Net.

**Comment by Hallbergs** [comment]
Alrighty!

**Review by Hallbergs — APPROVED** [review]
Just made a quick overview. LGTM.

**Pull request merged**
