### PR TITLE
Implement Quick Access feature in LayerSwitcher

### LINKED ISSUE #1237: Update Active tab with additional features
**Description**
The following features are suggested to be added to the Active tab:
* State management of active layers
* UI updates
* Button and layer icons
* Settings for each layer
* Number indicator for active layers in tab
* Toggle layer visibility
* Remove layer
* Toggle all layer’s visibility
* Remove all layers
* Undo last action
* Number of active layers
* Place base layers at the bottom of the list

**Screenshots**
Will be added later.

### PR DESCRIPTION
**Pull request by linusfj**
This pull request introduces the `Quick Access` feature and additional enhancements as described in issue #1380.

Key features implemented include:
- `Quick Access` grouping in `LayerSwitcher` for access to frequently used layers.
- Filter functionality in `LayerSwitcher` for efficient layer management.
- Improved `Snackbar` notifications for layer toggling actions.
- Enhanced layer visibility indicators in `LayerSwitcher`.
- Improved `Draw Order` tab functionality for managing layer drawing order.
- Section for `Quick Access` in the admin UI.

Closes #1237, #1257, #1284, #1296, #1300, #1347, #1365, and #1380.

### CODE REVIEW

**Review by jacobwod — CHANGES_REQUESTED** [review]
## Intro
Overall, I think it's a good start for a much-needed addition to the most used tool in our app. **A lot of core functionality is there and works well!** 

With that in mind, it's important that we get this _really_ right before merge. Especially since, as far as I can tell, **there's no way to do a soft rollout of the new LayerSwitcher** (running side-by-side and switching in map config). It's either the old codebase or the one in this PR. 

Below are my findings, grouped into categories: a) `simpleMapConfig`, b) provided configs in Node's backend and c) with Halmstad's current config.

# A. Out-of-the-box with `simpleMapConfig`, no backend
## Multiple warnings from ESlint
Easy fix, ESlint tells what to do. Here's a sample:
Skärmavbild 2023-12-22 kl  08 45 36

## Missing `anchorEl`, shows up as warnings in `console``
Click around a little to get these guys:
Skärmavbild 2023-12-22 kl  08 41 36
I had to enter a layer details view and then on arrow click back to the list I got those warnings.

## No QuickLayers view in `simpleMapConfig`
I think that should be added in order to expose the new functionality to a broader public. I see you've prepared two configs in `App_Data`, so light version of that to the simple map config would be nice.

---

# B. With data provided in `new-backend/App_Data`, client set to `http://localhost:3002/api/v1`

## `?m=map_1` 
### Does not load at all
Blank screen Here's the output from `console`:
Skärmavbild 2023-12-22 kl  08 54 10
Looks as the new tool expects some keys that aren't provided in the supplied config.

## `?m=goteborg`

### Filtering
First of all: **the filtering works**! 👍 
One thing I note is that there's no auto-expand in this configuration, so I get match on things that I really don't see. I guess it could get confusing, especially as we have multiple nested levels. E.g. see below, we get match because there are some layers named "Bygg*" in the group that's collapsed.

Skärmavbild 2023-12-22 kl  09 02 29

## `?m=goteborg_inkl_quickLayersPresets_ver2``

### QuickLayers group 
This has to be enabled in Admin. Once enabled a quick access group shows on top. Overall, this function works! 👍 One thing I'd like to propose: **this should really get saved into `LocalStorage`**. It's nice to add my most frequently used layers to quick access, but when I come back tomorrow, I expect "my" quick layers to still be there.

### What's the `Settings` part doing?
All layers seem to have a `Settings` part in the detail view. I can't see anything there, besides the heading. Is something missing?

Skärmavbild 2023-12-22 kl  09 07 57

### CQL filtering
I don't see any requests or anything going on (perhaps there are no suitable layers to test in your config?) If this only works for vector layers, we shouldn't even show the option for WMS layers. Currently, it's a bit confusing. E.g. screenshot below, I don't expect any bike paths to still show, given the CQL filter value:
Skärmavbild 2023-12-22 kl  09 15 59

### System layers in Draw order tab
Once enabled in Admin, they show up. But **there's no way to control opacity** anymore, as in the previous version of the tool. Please re-add.
image

### Own themes in Quick access layers
Clicking on the Themes button (screenshot 1) leads to a lot of warnings (screenshot 2):

Skärmavbild 2023-12-22 kl  09 28 19

Skärmavbild 2023-12-22 kl  09 27 38

### Attempt to load predefined themes leads to a crash, blank screen
As soon as I click _Load_ here:
Skärmavbild 2023-12-22 kl  09 29 41

We get a total crash with a rather long call stack, leading to `GroupLayer.js:
Skärmavbild 2023-12-22 kl  09 30 45

**I think it's a configuration issue though**, as it only happens with the first of the two pre-defined themes in Göteborg's supplied config. The other theme does not crash the app. It doesn't load anything either, but I guess it's because of missing layers in supplied config.

---

# C. With Halmstad's current config

As in previous parts (A & B), a lot of things just work as expected. 👍 

One thing remains though:

## The layer's detail view is blank
For reasons unknown, this happens for both layers and background layers. Our config can be [found here](https://karta.halmstad.se/api/v2/config/ext).

https://github.com/hajkmap/Hajk/assets/110222/8f7871bf-3925-4f01-a08b-952f0984396c


---

# Reminder: things that already work well
- Filtering!
- Draw order tab, when enabled in settings. **But I'm missing a way to quickly toggle a layer's visibility** in this view. Also, there's a lot of empty gray space at top of the tab.
- Quick access layers (apart from the fact that they disappear on app reload). The rest is fine: **import, export, switching between configurations**. Even saving parts of Hajk layer groups works - fantastic! Good job!

**Comment by elizabethgbg** [comment]
Hi!
FYI, we have just found a bug in the search layers and groups function.

The bug means that the search function continues to filter out layers at a certain level in the tree structure within groups in which the function previously received a search hit. Previous search hits are thus displayed within the current groups while other layers, at a certain level in the tree structure, continue to be filtered out even though the search session has been ended.

We are looking into the bug further and hope to have it resolved as quickly as possible.
Our developer is currently on vacation so if any one want to hade a look at the bug with us - just get in touch!

**Comment by Hallbergs** [comment]
I'll hold off my review until the problems are sorted. I could look at the sorting bug with you, tell your developer(s) to contact me :)

**Comment by Hallbergs** [comment]
Did some digging regarding the double group filtering issue. Since `LayerGroup.js` is a `PureComponent`, only a shallow compare is done on the props. Since the key that controls if a layer is rendered or not lives deep in the layer-tree-prop, `LayerGroup` is not re-rendered.

Changing `LayerGroup` to a `Component` "solves" the issue. Bevare that this "fix" might lead to performance issues (since each comparison of the props will be much more expensive).

**Comment by linusfj** [comment]
The bugs related to the default configurations should now be resolved, and updated examples have been committed.

@jacobwod, could you check and confirm? Specifically, are you still encountering the issue with your configuration after attempting to re-save all configuration files in the admin UI?

**Comment by jacobwod** [comment]
Converted PR to draft to reflect the current state:
- functionality isn't ready for merge to `develop`, as discussed in a meeting last week
- PR branch contains unresolved conflicts

**Comment by linusfj** [comment]
Here is a summary of the current status:

The current method for saving `Quick Layers` involves using the "Add to Favorites" option, which utilizes `localStorage` for storage. The saved layers can subsequently be accessed by loading them. If you still want to proceed with the implementation as you've described, it could be considered a feature request.

Resolved issues:

- ESLint errors have been addressed.
- Auto-expansion functionality for groups during filtering has been added.
- The error message associated with `anchorEl` in the layer details view has been resolved.
- Configuration-related issues have been addressed. Example configurations have been updated to align with the new functionality in `LayerSwitcher`.
- The toggle for the detailed view of system layers has been enabled.

Unresolved issues:

- CQL filtering has not been thoroughly tested with a functioning layer. Feedback from someone actively using the filter would be highly beneficial.
- The issue with `anchorEl` that occurs when pressing the "Themes" button still persists. A temporary workaround that addresses the error is to avoid using the Tooltip component on the button.

**Comment by Hallbergs** [comment]
> Here is a summary of the current status:
> 
> The current method for saving `Quick Layers` involves using the "Add to Favorites" option, which utilizes `localStorage` for storage. The saved layers can subsequently be accessed by loading them. If you still want to proceed with the implementation as you've described, it could be considered a feature request.
> 
> Resolved issues:
> 
> * ESLint errors have been addressed.
> * Auto-expansion functionality for groups during filtering has been added.
> * The error message associated with `anchorEl` in the layer details view has been resolved.
> * Configuration-related issues have been addressed. Example configurations have been updated to align with the new functionality in `LayerSwitcher`.
> * The toggle for the detailed view of system layers has been enabled.
> 
> Unresolved issues:
> 
> * CQL filtering has not been thoroughly tested with a functioning layer. Feedback from someone actively using the filter would be highly beneficial.
> * The issue with `anchorEl` that occurs when pressing the "Themes" button still persists. A temporary workaround that addresses the error is to avoid using the Tooltip component on the button.

Thanks for the summary and the resolved issues!

An addition to the unresolved issues:
- Rendering performance issues. As shown in the last code group meeting, the layer-switcher becomes way to slow in maps with +300 (ish) layers.  We'll have to look into the possibility of changing how the layer-items are rendered to increase performance.

I am looking forward to test-results from other Hajk-organizations.

**Comment by maan002** [comment]
Two suggestions:

1. Make it possible in Admin to configure the number of characters that the user must enter before the filtering/searching begin. To force a filtering with less number of characters you should press <Enter>.
2. Perhaps add the possibility to the user to keep all layer's in a group when the group name is hit by the filter. Now you will get an empty group.

**Comment by linusfj** [comment]
I have addressed the rendering performance issues. By reverting to `React.PureComponent` and optimizing the state management methods `resetFilterStatus` and `handleFilterValueChange`, performance has been notably improved, especially in map configurations with many layers.

**Comment by jacobwod** [comment]
## Intro
_This is a follow-up to my [initial review](https://github.com/hajkmap/Hajk/pull/1437#pullrequestreview-1794173612)._

## Findings

### Warnings
On initial launch, console warnings still prevail. 
Skärmavbild 2024-02-14 kl  13 44 39

### The UI (fonts, line heights, more) seem "off"
Compare the new one:
Skärmavbild 2024-02-14 kl  13 50 10


With the current look:
Skärmavbild 2024-02-14 kl  13 50 23

I don't see why we should change the ratio between font size and line heights - the Material UI defaults are well-thought out and should remain.

### Still blank details view

https://github.com/hajkmap/Hajk/assets/110222/096433e8-a535-4225-91ee-ab2f88e2805b

## Unacceptably many re-renderings when hovering a basic UI elements

This has been "felt" by many but I don't think we've done any actual tests. Here it is. 

### Current `develop`
Note how quickly the icon state changes. Also, the render time (in ms, in the right panel - 10 ms in the first render commit, 13 ms in the sixth). Also, there are no renderings related to any component of LayerSwitcher.

https://github.com/hajkmap/Hajk/assets/110222/a43f4e5f-7db9-48e4-b85d-a320178a089d

### This PR
The icon state is really sluggish (unthrottled machine). Render time (first and sixth render commit) is 20-30x the previous values. A lot of rendering related to LayerSwitcher occurs. 

https://github.com/hajkmap/Hajk/assets/110222/cedebf49-b126-4e00-84f2-3e9e79707d51


## Conclusion
It took me a considerable amount of time to write the first review. (It also took a while to prepare this one.) 

As I've shown above, multiple issues from the first review still exist (both easy ones [like the warnings] and harder ones [like the performance issue]). 

**Given these facts, I stop here and will not continue with a full-fledged review. In my opinion, this code is far from being ready for a merge.**

**Comment by jesade-vbg** [comment]
Here is some things I noticed.

**I can't scroll at all**

no-overflow-scroll

**Depth warning (One of the reasons it's laggy?)**

depth-warning

**Can toggle when nothing below** 

can-toggle-when empty

**Pull request closed without merging**
