### PR TITLE
Updatecoord/vbg

### PR DESCRIPTION
**Pull request by hitomin21**
Coordinates tool now allows users to modify the coordinates in the textboxes and the feature on the map will be moved accordingly. Two buttons have been added.

One for zooming in, and panning, on the selected location and one for only panning to the selected location.

@persoderstrom  @perosoderstrom Can you take a look?

The version in the pull request looks like this:
bild

closes https://github.com/hajkmap/Hajk/issues/482

Note that I did not remove addInteraction and removeInteraction (it looks like this in the diff) but code was added in the middle.

### CODE REVIEW

**Review by persoderstrom — COMMENTED** [review]
@hitomin21 It's working good!
Maybe you should add a friendly message if a user types in NaN by mistake (or deliberately as I did). If you do and try to Zoom or Pan you get an error page. 
Alternatively disable Zoom/Pan if the input filelds are not numbers.

**Comment by hitomin21** [comment]
I have fixed so there is no error page when non-finite numbers are inserted so users will not be presented with the error page that you described.

There is one remaining problem, if a user writes a very large number and clicks zoom or pan, the openlayers function that would zoom or pan hangs. No error page is shown and the page freezes until the user refreshes. Perhaps this is ok? I think adding extent checking would require changes to the tool configuration and therefore an admin update. I am not sure it is worth it in this case.

Per: What do you think?

**Comment by persoderstrom** [comment]
@hitomin21 Good!
One thing that might happen is that a user edit a coordinate and by mistake delete the decimal point, which increase the number by a factor of 1000. I tested and that does not hang the page. You have to write numers greater than 10e20 to hang the map. So, if there is not a simple way to get the map extent, leave it as it is.

**Comment by hitomin21** [comment]
I pushed the error handling code now, please take a look again.

**Comment by persoderstrom** [comment]
The error handling works ok. 
But when you have edited a coordinate and panned and then close the tool you get an error page.

**Review by jacobwod — CHANGES_REQUESTED** [review]
Two things:
- You seem to use old Prettier as you're commits remove all trailing commas. Please ensure you're up-to-date (`npm up` should be enough but you can also do `rm node_modules && git pull && npm i`).
- The error handling you added doesn't seem to do any error recovery whatsoever – you just return from the `catch`.

**Comment by hitomin21** [comment]
I have fixed the error that you mentioned Per and ran Prettifier on the code.

Before I push it, @jacobwod please see below.

Regarding the error recovery, when invalid coordinates are entered into the box I thought that the user might be in the middle of modifying them and it is best not to show an alert popup with a message. Do you think that would be preferred? The function updateTransforms calculates the new transformed coordinates but since the inputted data is invalid it is best just to quit the function so no new faulty transferred data is written to the gui.

**Comment by jacobwod** [comment]
@hitomin21, I can't see your code until you've pushed it to this branch (and there's no harm doing it as the PR isn't merged yet). 

Also, I don't see why you use `try/catch` the way you do: that should be used for unexpected errors and recovery from them. In this case you expect that almost every keypress will result in an incomplete value that can't be parsed, and this throws an error, of course. But it shouldn't go that far: you should reject early in the `handleInput` method, and continue parsing only when some specified conditions of the input value are fulfilled (for example the input has a specific length, contains `.`, etc -  use a [`/someRegex/.test()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test#examples) to check if the condition is fulfilled).

**Comment by hitomin21** [comment]
I've pushed now.

There is verification in handleInput, the input will be parsed as floats and are verified that they are not NaN and that they are finite.

The remaining problem is mainly if the inputted numbers are in range for the transform, which would cause openlayers to throw an exception. This is what I mentioned above regarding that we would likely have to add an extent for each configured transform for the tool.

**Review by jacobwod — CHANGES_REQUESTED** [review]
@hitomin21, I still feel that the `handleInput`, which will run a lot when user is typing, is a bit too heavy, and therefore resource-intensive. 

The way you grab values (by traversing the DOM and looking for parent's parent) is also error-prone, perhaps there is some other way you could extract those values?

**Comment by jacobwod** [comment]
Perhaps you could re-think the way that validation is done too? There are great helpers in MUI, please take time to ensure you're using them, e.g. in the TextField, to handle validation of user input. Everything is well-documented [right here](https://material-ui.com/components/text-fields/#validation).

**Comment by hitomin21** [comment]
I added so we use the error attributes of MUI to show the error messages to the user. The field becomes red and there is message to the user that it should input a valid number now.

I profiled the JS with dev tools and it does not use so much performance when I keep changing the numbers a lot so I think we should be ok performance-wise. I put the input validation at the top of the code so errors will be detected directly instead of after the DOM was parsed although that would only help when users write incorrect numbers of course.

Regarding using the DOM, can we accept that if we modify the structure of the tool that we also has to updated how the code finds the sibling to the field that was modified?

**Comment by jacobwod** [comment]
Please push the code to the branch so that I can see the changes you're talking about. Thank you.

**Comment by hitomin21** [comment]
I pushed the code now, sorry I forgot to click it yesterday. I merged master into the branch but I want to test it some more, I will write here after I have tested it.

**Comment by hitomin21** [comment]
I have tested it and it works with the current master so please review it again @jacobwod

**Review by jacobwod — CHANGES_REQUESTED** [review]
Hi @hitomin21! A quick look at the `handleInput` tells me that it should be better now - you seem to do an early return when invalid values occur. I haven't tested it yet however.

Still some minor improvements that can be made: please replace `var` with either `const` or `let` depending on situation. (I usually go with `const` unless I see that I need to re-assign a variable - in that case I just change it to `let`.)

**Comment by hitomin21** [comment]
I modified all the var to let and const now, thanks for that.

**Review by sweco-sesqqq — APPROVED** [review]
I just ran the code locally and everything seems to be working.

There seems to be some stability issues connected to handle input still, look in to it if you want to! :)

**Pull request merged**
