### PR TITLE
Added possibility to buffer from the Sketch plugin

### PR DESCRIPTION
**Pull request by Albinahmetaj**
Issue #1310 

This branch represents the possibility for the user to buffer directly from the sketch plugin as an MUI accordion component.
It follows the same structure as the Buffer plugin with a Buffer component acting as parent, a Buffermodel and a Bufferview. But this time it was developed using functional components.

### CODE REVIEW

**Review by Hallbergs — DISMISSED** [review]
Looks good, works great - good job!

**Review by Hallbergs — CHANGES_REQUESTED** [review]
Sorry for keeping you waiting... Haven't really had any time to Hajk the last weeks.

Anyways:
- When enabling the buffer-tool, and clicking a feature in the map, the info-click window opens. This can be avoidied by enabling clicklock when enabling the buffer selection.
- Would it be possible to combine some of the state that are passed via props into a state-object? If you want, we could have a look at it together?

**Comment by Albinahmetaj** [comment]
No problem, I appreciate the review and the comment.

Regarding the changes, sounds great I'll take a look at it.
Absolutely, if you got the time. Just give me a heads up

**Review by Hallbergs — CHANGES_REQUESTED** [review]
See: https://github.com/hajkmap/Hajk/pull/1480#pullrequestreview-1905505250

It would be nice if we could avoid the eslint-disablings. Would it be feasible to destructure here as well?

**Review by Hallbergs — APPROVED** [review]

**Review by jacobwod — DISMISSED** [review]

**Review by Hallbergs — APPROVED** [review]

**Pull request merged**
