### PR TITLE
added possibility to set point size

### LINKED ISSUE #1373: Sketch plugin: point size
Add option to be able to change point size.

### PR DESCRIPTION
**Pull request by Albinahmetaj**
Fixes #1373

### CODE REVIEW

**Comment by jesade-vbg** [comment]
Nice addition!

Did a few quick tests but havn't checked the code.

Noticed that a default value isn't set in the slider (undefined). This goes away nicely when sliding.

image

And a little MUI error in console each time you move the slider.

image

I also wonder if it could be possible to have the slider with smaller steps, maybe 2-4px, and add custom marks for "Liten, Mellan, Stor". Or what do you think? https://mui.com/material-ui/react-slider/#custom-marks

**Comment by Albinahmetaj** [comment]
> Nice addition!
> 
> Did a few quick tests but havn't checked the code.
> 
> Noticed that a default value isn't set in the slider (undefined). This goes away nicely when sliding.
> 
> image
> 
> And a little MUI error in console each time you move the slider.
> 
> image
> 
> I also wonder if it could be possible to have the slider with smaller steps, maybe 2-4px, and add custom marks for "Liten, Mellan, Stor". Or what do you think? https://mui.com/material-ui/react-slider/#custom-marks


Thanks for the review, I will see to it!

**Review by jacobwod — DISMISSED** [review]

**Review by Hallbergs — DISMISSED** [review]
lgtm

**Review by Hallbergs — APPROVED** [review]
lgtm

**Pull request merged**
